FROM python:3.9-slim

WORKDIR /app

COPY api/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api /app

COPY certs /certs

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "/certs/api-key.pem", "--ssl-ca-certs", "/certs/ca-cert.pem", "--ssl-cert-reqs", "2", "--ssl-certfile", "/certs/api-cert.pem"]
