# Dockerfile para el Backend
FROM python:3.9-slim

# Instalar dependencias adicionales (si es necesario)
RUN apt-get update && apt-get install -y python3-tk libgtk-3-0 libx11-6

# Directorio de trabajo
WORKDIR /app

# Copiar requirements.txt e instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar la aplicación
COPY . .

# Copiar certificados (si están disponibles en el host)
COPY certs /certs

# Exponer el puerto 8000
EXPOSE 8000

# Comando para iniciar la aplicación con SSL
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--ssl-keyfile", "/certs/api-key.pem", "--ssl-ca-certs", "/certs/ca-cert.pem", "--ssl-cert-reqs", "2", "--ssl-certfile", "/certs/api-cert.pem"]
